trigger:
  - main  # Or your Git branch name

pool:
  vmImage: 'windows-latest'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      options: '-X'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

